In [1]:
from vrptw_base import *
from genetic_algorithm import *
import numpy as np

In [2]:
filepath = r"solomon-100\r101.txt"

In [3]:
graph = VrptwGraph(filepath,0.2)

In [4]:
ga = GeneticAlgorithm(graph)

In [5]:
initial_solution = ga.get_nnh_solution()

In [6]:
initial_solution.travel_distance

2442.312436145263

In [7]:
initial_solution.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  72,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0])

In [8]:
ga.fitness_value(initial_solution)

0.40944802360271093

In [9]:
best_sol = ga.run_algorithm(10,25)

found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [10]:
best_sol.travel_distance

1588.3658942564814

In [11]:
best_sol.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  80,  76,   0,  89,  93,
         0,   6,  94,  96,  91,  98,   0,  40,  74,   4,  25,  12,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  13,   0,
        77,  50,  68,  24,   2,   0,  31,  88,   7,   8,  46,  10,  32,
        90,   0,  99,  85,  84,  43,  22,   0,  59,  92, 100,  61,   0,
        57,  15,  41,   3,  34,   0,  21,  73,   9,  66,   0,   5,  82,
        19,  49,   0,  83,   0,  72,  75,   0,  30,  51,   0,  42,  14,
        44,  38,  11,  64,   0,  45,  47,   0])

In [12]:
ga.initial_solution.travel_distance

2442.312436145263

In [13]:
best_sol

In [14]:
pop = ga.generate_population(50)

found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [15]:
pop = ga.generate_population(50)
population_fitnesses = [solution.get_total_fitness() for solution in pop]
population_best_fitness = max(population_fitnesses)
index = population_fitnesses.index(population_best_fitness)
best_sol = pop[index]


found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [16]:
pop = ga.generate_population(50)
population_fitnesses = [solution.get_total_fitness() for solution in pop]
population_best_fitness = max(population_fitnesses)
index = population_fitnesses.index(population_best_fitness)
best_sol = pop[index]

p1,p2=ga.choose_parents(pop,population_fitnesses)

found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [17]:
p1.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  72,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  56,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0])

In [18]:
[  0,  53,  58,   0,  27,  17,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,  0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        72,   9,  66,   0,   5,  83,  82,  19,  49,   0,  22,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0]

[0,
 53,
 58,
 0,
 27,
 17,
 26,
 54,
 80,
 70,
 0,
 89,
 93,
 0,
 6,
 94,
 96,
 13,
 100,
 0,
 40,
 74,
 4,
 25,
 77,
 0,
 52,
 18,
 60,
 48,
 0,
 69,
 1,
 0,
 95,
 97,
 37,
 91,
 0,
 12,
 76,
 50,
 68,
 24,
 17,
 0,
 31,
 88,
 7,
 8,
 46,
 10,
 32,
 35,
 0,
 99,
 85,
 84,
 43,
 55,
 0,
 59,
 92,
 98,
 61,
 86,
 57,
 56,
 0,
 2,
 87,
 41,
 3,
 34,
 20,
 0,
 21,
 73,
 72,
 9,
 66,
 0,
 5,
 83,
 82,
 19,
 49,
 0,
 22,
 75,
 67,
 79,
 78,
 0,
 33,
 81,
 90,
 0,
 30,
 51,
 0,
 42,
 14,
 44,
 16,
 38,
 0,
 62,
 11,
 64,
 0,
 45,
 47,
 71,
 0,
 29,
 23,
 0,
 15,
 0,
 39,
 65,
 0,
 63,
 36,
 0]

In [19]:
p2.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  77,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  80,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  72,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0])

In [20]:
p1.travel_distance,p2.travel_distance

(2435.5745516600064, 2437.246316644187)

In [21]:
p1.check_capacity_constrain(),p1.check_time_constrain(),p2.check_capacity_constrain(),p2.check_time_constrain()

(True, True, True, True)

In [22]:
c1,c2= ga.crossover(p1, p2)

cross over point:69


In [23]:
c1.check_capacity_constrain(),c1.check_time_constrain(),c2.check_capacity_constrain(),c2.check_time_constrain()

(True, True, True, True)

In [24]:
c1.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  72,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  75,  67,  79,
        78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,  16,
        38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,   0,
        15,   0,  39,  65,   0,  63,  36,   0])

In [25]:
x=[  0,  53,  58,   0,  27,  17,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,  0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        72,   9,  66,   0,   5,  83,  82,  19,  49,   0,  22,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0]

In [26]:
p1==c2

False

In [27]:
c2.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  77,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  80,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  75,  67,  79,
        78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,  16,
        38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,   0,
        15,   0,  39,  65,   0,  63,  36,   0])

In [28]:
c1.travel_distance,c2.travel_distance

(2430.0301702802676, 2437.173834761708)

In [29]:
m1 = ga.mutation(c1, 0.1)
m2 = ga.mutation(c2, 0.1)


counter >100
counter >100


In [30]:
m1.check_capacity_constrain(),m1.check_time_constrain(),m2.check_capacity_constrain(),m2.check_time_constrain()

(True, True, True, True)

In [31]:
m1 = ga.mutation(c1, 0.1)
m2 = ga.mutation(c2, 0.1)

t1 = ga.apply_tabu_search(m1, 100, 10)
t2 = ga.apply_tabu_search(m2, 100, 10)


counter >100
counter >100
found feasible better solution from tabu search
found feasible better solution from tabu search


In [32]:
t1.check_capacity_constrain(),t1.check_time_constrain(),t2.check_capacity_constrain(),t2.check_time_constrain()

(True, True, True, True)

In [33]:
t1==c1

False

In [34]:
t2==c2

False

In [35]:
gen_size = 10
pop_size = 30
population = ga.generate_population(50)
population_fitnesses = [solution.get_total_fitness() for solution in population]
population_best_fitness = max(population_fitnesses)
index = population_fitnesses.index(population_best_fitness)
best_sol = population[index]

for g in range(gen_size):
    print(f"gen:{g}")
    new_population = []
    for _ in range(pop_size):
        population_fitnesses = [solution.get_total_fitness() for solution in population]
        population_best_fitness = max(population_fitnesses)
        index = population_fitnesses.index(population_best_fitness)
        best_sol = population[index]
        p1,p2=ga.choose_parents(population,population_fitnesses)
        c1,c2= ga.crossover(p1, p2)
        m1 = ga.mutation(c1, 0.1)
        m2 = ga.mutation(c2, 0.1)
        t1 = ga.apply_tabu_search(m1, 100, 10)
        t2 = ga.apply_tabu_search(m2, 100, 10)
        new_population.append(t1)
        new_population.append(t2)

    population_fitnesses = [solution.get_total_fitness() for solution in population]
    population_best_fitness = max(population_fitnesses)
    index = population_fitnesses.index(population_best_fitness)
    best_sol = population[index]
    print(f"best sol travel_distance ={best_sol.travel_distance}")
    print(f"best solution path: {best_sol.travel_path}")
    population = new_population


found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [36]:
best_sol.check_capacity_constrain()

True

In [37]:
best_sol.check_time_constrain()

True

In [38]:
best_sol.travel_distance

1619.8979309269855

In [39]:
best_sol.travel_path

array([  0,  53,  58,   0,  29,  12,  26,  54,  80,  77,   0,  89,  93,
         0,   6,  94,  96,  97, 100,   0,  40,  72,   4,  25,  39,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  37,  91,   0,  76,
        50,  68,  24,   0,  31,  88,   7,   8,  46,  36,  32,  66,   0,
        99,  85,  84,   0,  59,  92,  98,  86,  38,  57,  56,  23,   0,
         2,  87,   9,  20,   0,  21,  73,  22,   3,   0,   5,  83,  82,
        19,  49,   0,  67,  79,  78,   0,  33,  81,  51,   0,  30,  90,
         0,  42,  14,  44,  16,   0,  62,  11,  64,   0,   0,   0,   0,
         0,   0])

In [40]:
x=[  0,  17,  58,   0,  27,  21,  26,  66,   9,  70,   0,  89,  93,
         0,   6,  94,  96,  59, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  83,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  85,   0,  31,  88,   7,   8,  46,  64,
        32,   0,  99,  84,  43,  55,   0,  13,  92,  98,  61,   0,   2,
        87,  41,   3,  34,  20,   0,  28,   0,  73,  82,  19,  49,   0,
        72,  75,  67,  79,  78,   0,  33,  81,   0,  30,  51,   0,  42,
        14,  44,   0,  62,  11,   0]

In [41]:
ga.get_total_num_vehicles(x)

19

In [42]:
travel_path_copy = copy.deepcopy(path)
delete_idx = []
for i, customer in enumerate(path):
    print(f"i:{i}")
    if i > len(path) - 2:
        break

    if customer == 0 and path[i + 1] == 0:
        delete_idx.append(i+1)

travel_path_copy = np.delete(travel_path_copy, delete_idx)



NameError: name 'path' is not defined

In [ ]:
path