In [11]:
from vrptw_base import *
from genetic_algorithm import *
import numpy as np
from vprtw_aco_figure import *

In [12]:
filepath = r"solomon-100\r101.txt"

In [13]:
graph = VrptwGraph(filepath,0.2)

In [14]:
ga = GeneticAlgorithm(graph)

In [15]:
initial_solution = ga.get_nnh_solution()

In [16]:
initial_solution.travel_distance

2442.312436145263

In [17]:
initial_solution.travel_path

array([  0,  53,  58,   0,  27,  28,  26,  54,  80,  70,   0,  89,  93,
         0,   6,  94,  96,  13, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  17,   0,  31,  88,   7,   8,  46,  10,
        32,  35,   0,  99,  85,  84,  43,  55,   0,  59,  92,  98,  61,
        86,  57,  56,   0,   2,  87,  41,   3,  34,  20,   0,  21,  73,
        22,   9,  66,   0,   5,  83,  82,  19,  49,   0,  72,  75,  67,
        79,  78,   0,  33,  81,  90,   0,  30,  51,   0,  42,  14,  44,
        16,  38,   0,  62,  11,  64,   0,  45,  47,  71,   0,  29,  23,
         0,  15,   0,  39,  65,   0,  63,  36,   0])

In [18]:
ga.fitness_value(initial_solution)

0.40944802360271093

In [19]:
import numpy as np
import random
from vprtw_aco_figure import VrptwAcoFigure
from vrptw_base import VrptwGraph, PathMessage
from ant import Ant
from threading import Thread, Event
from queue import Queue
from concurrent.futures import ThreadPoolExecutor
import copy
import time
from multiprocessing import Process
from multiprocessing import Queue as MPQueue
import numpy as np
import random
from vprtw_aco_figure import VrptwAcoFigure
from vrptw_base import VrptwGraph, PathMessage
from ant import Ant
from threading import Thread
from queue import Queue
import time

In [20]:
path_queue_for_figure = MPQueue()
best_sol = ga.run_algorithm(10,25,path_queue_for_figure)

found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu search
found feasible better solution from tabu

In [21]:
best_sol.travel_distance

1693.4976699022372

In [22]:
best_sol.travel_path

array([ 0, 53, 58,  0, 27, 28, 26, 54, 80, 70,  0, 89, 13,  0,  6, 94, 96,
       93,  0, 40, 74,  4, 25, 77,  0, 52, 18, 60, 48,  0, 69,  1,  0, 95,
       91, 37, 97,  0, 12, 76, 50, 68, 24,  0, 31, 88,  7,  8, 62, 10, 32,
       35,  0, 99, 85, 84, 43, 55,  0, 59, 92, 98, 61, 86, 57,  0,  2, 87,
       41,  3,  0, 21, 73, 65, 66,  0,  5, 83, 82, 19, 49,  0, 72, 75, 67,
       39, 78,  0, 33, 81,  0, 30, 51,  0, 42, 14, 44, 16,  0, 11, 63,  0,
       45,  0])

In [23]:
best_sol.get_num_of_customers()

82

In [31]:
m1 = ga.mutation(c1, 0.1)
m2 = ga.mutation(c2, 0.1)

t1 = ga.apply_tabu_search(m1, 100, 10)
t2 = ga.apply_tabu_search(m2, 100, 10)


counter >100
counter >100
found feasible better solution from tabu search
found feasible better solution from tabu search


In [32]:
t1.check_capacity_constrain(),t1.check_time_constrain(),t2.check_capacity_constrain(),t2.check_time_constrain()

(True, True, True, True)

In [ ]:
best_sol.check_capacity_constrain()

In [ ]:
best_sol.check_time_constrain()

In [38]:
best_sol.travel_distance

1619.8979309269855

In [39]:
best_sol.travel_path

array([  0,  53,  58,   0,  29,  12,  26,  54,  80,  77,   0,  89,  93,
         0,   6,  94,  96,  97, 100,   0,  40,  72,   4,  25,  39,   0,
        52,  18,  60,  48,   0,  69,   1,   0,  95,  37,  91,   0,  76,
        50,  68,  24,   0,  31,  88,   7,   8,  46,  36,  32,  66,   0,
        99,  85,  84,   0,  59,  92,  98,  86,  38,  57,  56,  23,   0,
         2,  87,   9,  20,   0,  21,  73,  22,   3,   0,   5,  83,  82,
        19,  49,   0,  67,  79,  78,   0,  33,  81,  51,   0,  30,  90,
         0,  42,  14,  44,  16,   0,  62,  11,  64,   0,   0,   0,   0,
         0,   0])

In [40]:
x=[  0,  17,  58,   0,  27,  21,  26,  66,   9,  70,   0,  89,  93,
         0,   6,  94,  96,  59, 100,   0,  40,  74,   4,  25,  77,   0,
        52,  18,  60,  83,   0,  69,   1,   0,  95,  97,  37,  91,   0,
        12,  76,  50,  68,  24,  85,   0,  31,  88,   7,   8,  46,  64,
        32,   0,  99,  84,  43,  55,   0,  13,  92,  98,  61,   0,   2,
        87,  41,   3,  34,  20,   0,  28,   0,  73,  82,  19,  49,   0,
        72,  75,  67,  79,  78,   0,  33,  81,   0,  30,  51,   0,  42,
        14,  44,   0,  62,  11,   0]

In [41]:
ga.get_total_num_vehicles(x)

19

In [42]:
travel_path_copy = copy.deepcopy(path)
delete_idx = []
for i, customer in enumerate(path):
    print(f"i:{i}")
    if i > len(path) - 2:
        break

    if customer == 0 and path[i + 1] == 0:
        delete_idx.append(i+1)

travel_path_copy = np.delete(travel_path_copy, delete_idx)



NameError: name 'path' is not defined

In [ ]:
path